# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('orgtype', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('machineid', models.CharField(max_length=10)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
