# Generated by Django 2.0.3 on 2018-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldmaterhttp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.CharField(max_length=10)),
                ('machine_status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('MN', 'MAINTENANCE')], default='OFF', max_length=3)),
                ('ambient_temp', models.IntegerField()),
                ('water_temp', models.IntegerField()),
                ('set_temp', models.IntegerField()),
                ('temp_set_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
